### ISSUE TITLE
Proxy Settings "Nginx Proxy Manager" web UI

### ISSUE THREAD

**Issue by Haecky** [gurucomputing/headscale-ui#112]
I need settings for "Nginx Proxy Manager" web UI

 how do you secure the login?

Please help

**Comment by routerino** [comment]
As I do not actively use nginx proxy manager, and given the lack of supporting detail, I don't have an answer for you.

Information about security can be found in [SECURITY.MD](./SECURITY.md)

**Comment by ithakaa** [comment]
> I need settings for "Nginx Proxy Manager" web UI
> 
> 
> 
>  how do you secure the login?
> 
> 
> 
> Please help

I have a working install

**Comment by du724931566** [comment]
also need settings for "Nginx Proxy Manager" web UI, please
thanks a lot

**Comment by ithakaa** [comment]
Replace <server_ip>

```
proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k; 
proxy_ssl_server_name on;
location /web/ {
    proxy_set_header        Host                $http_host;
    proxy_set_header        X-Real-IP           $remote_addr;
    proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto   $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection \"upgrade\";
    proxy_redirect http:// https://;
    proxy_pass http://<server_ip>:8090/web/;
}
location / {
    proxy_set_header        Host                $http_host;
    proxy_set_header        X-Real-IP           $remote_addr;
    proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto   $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection \"upgrade\";
    add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
    proxy_redirect http:// https://;
    proxy_buffering off;
    proxy_intercept_errors  on;
    proxy_http_version      1.1;
    proxy_pass http://<server_ip>:8088/;
  }
```

**Comment by du724931566** [comment]
> Sorry for the late reply
> 
> Do the usual stuff for a host entry, leave custom locations empty, and then replace <server_ip> and add the below to the advanced section of Nginx Proxy Manager for the host
> 
> ```
> proxy_buffer_size   128k;
> proxy_buffers   4 256k;
> proxy_busy_buffers_size   256k; 
> proxy_ssl_server_name on;
> location /web/ {
>     proxy_set_header        Host                $http_host;
>     proxy_set_header        X-Real-IP           $remote_addr;
>     proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
>     proxy_set_header        X-Forwarded-Proto   $scheme;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection \"upgrade\";
>     proxy_redirect http:// https://;
>     proxy_pass http://<server_ip>:8090/web/;
> }
> location / {
>     proxy_set_header        Host                $http_host;
>     proxy_set_header        X-Real-IP           $remote_addr;
>     proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
>     proxy_set_header        X-Forwarded-Proto   $scheme;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection \"upgrade\";
>     add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
>     proxy_redirect http:// https://;
>     proxy_buffering off;
>     proxy_intercept_errors  on;
>     proxy_http_version      1.1;
>     proxy_pass http://<server_ip>:8088/;
>   }
> ```

excuse me,i have try several times to put this into Custom Nginx Configuration
but it warming : Please note, that any add_header or set_header directives added here will not be used by nginx. You will have to add a custom location '/' and add the header in the custom config there.

the both proxy_pass settings had been changed to my container ip and port

the container is running ,web up, but the api test failed 
i dont konw what should i do now, so plagued
i used Nginx Proxy Manager
Looking forward to your help

**Comment by ithakaa** [comment]
Do you have a properly working NPM with an SSL CRT you are using with other applications ?

**Comment by appleimperio** [comment]
@ithakaa I try your config and I'm getting the error "Client sent an HTTP request to an HTTPS server." but I think It's because in the 
```
location /web/ {
    proxy_set_header        Host                $http_host;
    proxy_set_header        X-Real-IP           $remote_addr;
    proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto   $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection \"upgrade\";
    proxy_redirect http:// https://;
    proxy_pass http://<server_ip>:8090/web/;
```
 the last line should be https. but even when I change it I get a withe screen no errors just when accessing the ui the other part works fine. Any idea what I'm doing wrong?

**Comment by ithakaa** [comment]
> the last line should be https.

it works for me
are you using a valid ssl crt with NPM ?

**Comment by appleimperio** [comment]
Yes, I already have external clients running I just want to try the web-ui. Just to be clear the ports you use there. the location /web/ port is the one I have configured in Headscale-ui and the location / is the port I have configured for Headscale?

**Comment by ithakaa** [comment]
I've provided screenshots, might be easier this way

https://github.com/ithakaa/headscale-ui-npm/blob/main/README.md

**Comment by appleimperio** [comment]
Thank you very much. Your installation is with docker?

**Comment by ithakaa** [comment]
> Your installation is with docker?

yes

**Comment by appleimperio** [comment]
This is my compose 
```
version: '3.5'
services:
  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    restart: unless-stopped
    #ports:
    #  - 8011:8080
    volumes:
      - /srv/dev-disk-by-uuid-36ffb5ee-7f60-4aea-bc0c-45c47cfbd3f7/containersdata/headscale/config:/etc/headscale
      - /srv/dev-disk-by-uuid-36ffb5ee-7f60-4aea-bc0c-45c47cfbd3f7/containersdata/headscale/data:/var/lib/headscale
    command: headscale serve
    networks:
      nginxproxymanager_default:

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    #ports:
    #  - 8443:443 # Use the port of your choice, but map it to 443 on the container
    networks:
      nginxproxymanager_default:  

networks:
  nginxproxymanager_default:
    external: true
```

can you share your compose. that way I will have everything the same. Thanks
