### ISSUE TITLE
Traefik working config & suggestion against default HTTPS

### ISSUE THREAD

**Issue by DennisGaida** [gurucomputing/headscale-ui#19]
A working traefik configuration may look like the following and you may add to your documentation:

```yaml=
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    networks:
      - traefik_proxy
    command: headscale serve
    volumes:
      - $DOCKERDIR/headscale/config:/etc/headscale
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.headscale-rtr.entrypoints=https"
      - "traefik.http.routers.headscale-rtr.rule=Host(`hs.${DOMAIN_PUBLIC}`)"
      ## Middlewares
      - "traefik.http.routers.headscale-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.headscale-rtr.service=headscale-svc"
      - "traefik.http.services.headscale-svc.loadbalancer.server.port=8080"

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.headscale_ui-rtr.entrypoints=https"
      - "traefik.http.routers.headscale_ui-rtr.rule=Host(`hs.${DOMAIN_PUBLIC}`) && PathPrefix(`/web`)"
      ## Middlewares
      - "traefik.http.routers.headscale_ui-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.headscale_ui-rtr.service=headscale_ui-svc"
      - "traefik.http.services.headscale_ui-svc.loadbalancer.server.port=443"
      - "traefik.http.services.headscale_ui-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.headscale_ui-svc.loadbalancer.serversTransport=disableSSLCheck@file"
```
And an additional config file `whatevername.yml`:
```yaml
http:
  serversTransports:
    disableSSLCheck:
      insecureSkipVerify: true
```

Since we are using a reverse proxy anyways, is the internal HTTPS with a self-signed certificate really necessary? I really dislike having to add an additional `insecureSkipVerify` configuration to either Caddy or traefik. ~~I see that the service really is served via `127.0.0.1:2019` - why not expose that port to `0.0.0.0`? What's the benefit of having Caddy inside the container?~~

~~I would happily forward the reverse proxy to `<container>:2019` without having to deal with the self-signed certificate.~~
