### ISSUE TITLE
HAProxy over OPNSense - how to set it up?

### ISSUE THREAD

**Issue by vampywiz17** [gurucomputing/headscale-ui#45]
Hello there!

Here my config:

```
version: '3.5'
services:
  headscale:
    image: headscale/headscale:latest-alpine
    container_name: headscale
    volumes:
      - type: bind
        source: /home/vamp/headscale/container-config
        target: /etc/headscale
      - type: bind
        source: /home/vamp/headscale/container-data/data
        target: /var/lib/headscale

    ports:
      - 16666:8080
    command: headscale serve
    restart: unless-stopped
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
      - 16667:80
```

I use OPNSense firewall with HAProxy. 

Here the settings:

Set two backend, one of assign to my docker host port 16666, the other to the 16667. I create one Frontend (TLS certificated) on my firewall port 443.  Create conditions and rules, that this domain names redirect to the correct backend:

- https://headscale.mydomain.org:443
- https://headscale-ui.mydomain.org:443

it work well, i access both site. The problem is the CORS ... i never set it up with HAproxy and not found any documentation that fit to HAProxy plugin with OPNSense (only "vanilla" HAproxy)

So anybody successfully set it up above similar configuration on OPNSense?
