### ISSUE TITLE
fatal: unable to access 'https://github.com/gurucomputing/headscale-ui/'

### ISSUE THREAD

**Issue by willzhang** [gurucomputing/headscale-ui#58]
** Supporting Details **
Provide the following:
* Browser Version: chrome 104.0.5112.102
* Headscale Version:  0.16.4-alpine 
* Any Browser Errors (`control+shift+i` in chrome to see)

**Describe the bug**
A clear and concise description of what the bug is. Screenshots if applicable

```
version: '3.5'
services:
  headscale:
    image: headscale/headscale:0.16.4-alpine
    container_name: headscale1
    volumes:
      - /data/headscale1/config:/etc/headscale
      - /data/headscale1/data:/var/lib/headscale
    ports:
      - 27896:8080
    command: headscale serve
    restart: unless-stopped
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
      - 9443:443
```

headscale-ui container have error and the web ui  can not access
```
root@ubuntu-vm:/data/scripts# docker logs -f headscale-ui
-- Fresh Install detected, setting up your dev environment --
-- Installing Source --
Cloning into 'headscale-ui'...
fatal: unable to access 'https://github.com/gurucomputing/headscale-ui/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
/staging/scripts/2-initialise.sh: 42: cd: can't cd to headscale-ui
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /data/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/data/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/home/.npm/_logs/2022-08-27T05_21_24_122Z-debug-0.log
Server bound to 0.0.0.0:3000 (IPv4)
Extension host agent listening on 3000

Ignoring option 'connection-token': Value must not be empty.
Web UI available at http://localhost:3000/?tkn=27eb12f2-4fda-4c77-b3fe-df5cc75322af
[05:21:24] Extension host agent started.
```

notes: my network not really good for accesss github,
